name: StrokePredictionML
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.21
  - pip
  - pip:
      - asttokens==2.0.5
      - backcall==0.2.0
      - comm==0.2.1
      - debugpy==1.6.7
      - decorator==5.1.1
      - exceptiongroup==1.2.0
      - executing==0.8.3
      - importlib-metadata==8.5.0
      - importlib_metadata==8.5.0
      - ipykernel==6.29.5
      - ipython==8.15.0
      - jedi==0.19.2
      - jupyter-client==8.6.0
      - jupyter-core==5.7.2
      - matplotlib-inline==0.1.6
      - nest-asyncio==1.6.0
      - packaging==24.1
      - parso==0.8.4
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - platformdirs==3.10.0
      - prompt-toolkit==3.0.43
      - psutil==5.9.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pygments==2.15.1
      - python-dateutil==2.9.0post0
      - pyzmq==25.1.2
      - setuptools==75.1.0
      - six==1.16.0
      - stack-data==0.2.0
      - tornado==6.4.2
      - traitlets==5.14.3
      - typing-extensions==4.11.0
      - wcwidth==0.2.5
      - wheel==0.44.0
      - absl-py==2.1.0
      - matplotlib
      - astunparse==1.6.3
      - bleach==6.2.0
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - flatbuffers==24.3.25
      - fonttools==4.55.3
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.68.1
      - h5py==3.12.1
      - idna==3.10
      - importlib-resources==6.4.5
      - joblib==1.4.2
      - kaggle
      - keras==3.7.0
      - kiwisolver==1.4.7
      - libclang==18.1.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - ml-dtypes==0.4.1
      - namex==0.0.8
      - numpy==2.0.2
      - opt-einsum==3.4.0
      - optree==0.13.1
      - pandas==2.2.3
      - pillow==11.0.0
      - protobuf==5.29.1
      - pyparsing==3.2.0
      - python-slugify==8.0.4
      - pytz==2024.2
      - requests==2.32.3
      - rich==13.9.4
      - scikit-learn==1.6.0
      - scipy==1.13.1
      - seaborn==0.13.2
      - tensorboard==2.18.0
      - tensorflow==2.18.0
      - tensorflow-addons
      - termcolor==2.5.0
      - text-unidecode==1.3
      - threadpoolctl==3.5.0
      - tqdm==4.67.1
      - tzdata==2024.2
      - urllib3==2.2.3
      - webencodings==0.5.1
      - werkzeug==3.1.3
      - wrapt==1.17.0
